### ISSUE TITLE
Unable to clone git repository from Azure DevOps to Windows Power Shell

### ISSUE THREAD

**Issue by anithamir** [UltimateDevOpsNCloud/IssuesFaced#2]
Getting below error while trying to clone git repository from Azure DevOps to Windows Power Shell
![image](https://github.com/UltimateDevOpsNCloud/IssuesFaced/assets/148305818/820eecf2-8c90-4e05-b2ec-8a71bb23fcf8)

**Comment by longflewtinku** [comment]
git clone <git url https://>
    or 
 your try ssh type is clone this time first your go to the git hub settings click  ssh key option  after add your genareate ssh key  after ssh type git url clone  now this is working

**Comment by anithamir** [comment]
Issue Resolved.
