### ISSUE TITLE
Error while trying to build the dotnet application in Azure DevOps

### ISSUE THREAD

**Issue by Nikhita-A** [UltimateDevOpsNCloud/IssuesFaced#3]
![image (1)](https://github.com/UltimateDevOpsNCloud/IssuesFaced/assets/148535211/67b8e932-93ec-4b25-82c2-f8ad45d65911)
![image (2)](https://github.com/UltimateDevOpsNCloud/IssuesFaced/assets/148535211/81bba92d-e066-4051-b6f4-bd8935a16b85)
![image](https://github.com/UltimateDevOpsNCloud/IssuesFaced/assets/148535211/3202e4fc-f5fe-4e91-8b31-35cfeceaf7b6)
![image(3)](https://github.com/UltimateDevOpsNCloud/IssuesFaced/assets/148535211/69d476fd-60f3-43a7-9211-0db327650f6e)

**Comment by gopikrishnayakkati** [comment]
It says no space available on that instance
Use t2 medium or t3 medium

**Comment by Nikhita-A** [comment]
It is t2 large actually

**Comment by Nikhita-A** [comment]
issue resolved. thank you!
